# Generated by Django 4.0.5 on 2022-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='song',
            name='file_location',
            field=models.SlugField(default='none'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='Unavailable'),
        ),
    ]
